#server:
#  port: 8764
#
#spring:
#  application:
#    name: service-turbine
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#      cors:
#        allowed-origins: "*"
#        allowed-methods: "*"
#
#turbine:
#  app-config: service-hi,service-hi2
#  aggregator:
#    clusterConfig: default
#  clusterNameExpression: new String("default")
#  combine-host: true
#  instanceUrlSuffix:
#    default: actuator/hystrix.stream

server:
  port: 8764

spring:
  application:
    name: service-turbine

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

turbine:
#  app-config: service-hi,service-hi2
#指定需要监控的servicename，多个service以,间隔
  app-config: service-feign
#指定集群名称，默认为default，当设立了多个集群时，可以在Hystrix指定集群名称来查看监控
  clusterNameExpression: new String("default")
#合并同一个host多个端口的数据
  combine-host-port: true
#  instanceUrlSuffix:
#    default: actuator/hystrix.stream