spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


server:
  port: 8881

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url: http://localhost:8761/eureka/
