server:
  port: 8766

spring:
  application:
    name: service-gateway
#
#  cloud:
#    gateway:
#      routes:
#        - id: prefix_route
#          uri: lb://service-client
#          predicates:
#            - Path=/sky/myHistrix
#          filters:
#            - name: Hystrix # Hystrix Filter的名称
#              args: # Hystrix配置参数
#                name: fallbackcmd #HystrixCommand的名字
#                fallbackUri: forward:/fallback #fallback对应的uri

#Hystrix的fallbackcmd的时间
#hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 5000
  cloud:
    gateway:
      default-filters:
        - Sky=true
#      default-filters:
#        - name: RequestRateLimiter
#          args:
#            key-resolver: "#{@remoteAddrKeyResolver}"
#            rate-limiter: "#{@customRateLimiter}"   # token
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: service-client #服务唯一ID标识
          uri: lb://service-client # 注册中心的服务id
          predicates:
            - Path=/client/** #请求转发
          filters:
            - StripPrefix=1 #切割请求，去除/client/
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
#        - id: hystrix
#          uri: lb://service-client
#          predicates:
#            - Path=/sky/**
#          filters:



#      routes:
#        - id: service-client
#          uri: lb://SERVICE-CLIENT
#          order: 0
#          predicates:
#            - Path=/client/**
#          filters:
#            - StripPrefix=1
#            - AddResponseHeader=X-Response-Default-Foo, Default-Bar

#  redis:
#    host: localhost
#    port: 6379


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#Hystrix的fallbackcmd的时间
#hystrix:
#  command:
#    fallbackcmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3000

#Hystrix的fallbackcmd的时间
#hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 5000

#logging:
#  level:
#    org.springframework.cloud.gateway: TRACE
#    org.springframework.http.server.reactive: DEBUG
#    org.springframework.web.reactive: DEBUG
#    reactor.ipc.netty: DEBUG

